import java.util.ArrayList;


public class ScheduleDisplay extends javax.swing.JPanel{
		public ArrayList<String> classesChosen = new ArrayList<String>();
		
		/**
		 * Creates new form ScheduleDisplay
		 */
		public ScheduleDisplay(ArrayList<String> classesChosen) {
			initComponents();
			classesChosen = this.classesChosen;
			this.setVisible(true);
		}

		/**
		 * This method is called from within the constructor to initialize the
		 * form. WARNING: Do NOT modify this code. The content of this method is
		 * always regenerated by the Form Editor.
		 */
		@SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated Code">
		private void initComponents() {

			jScrollPane2 = new javax.swing.JScrollPane();
			jTextArea2 = new javax.swing.JTextArea();
			list1 = new java.awt.List();

			jTextArea2.setColumns(20);
			jTextArea2.setRows(5);
			jTextArea2.setText("Student Schedule");
			jScrollPane2.setViewportView(jTextArea2);

			list1.add("Class 1");
			list1.add("Class 2");
			list1.add("Class 2");
			
			
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
			this.setLayout(layout);
			layout.setHorizontalGroup(layout
					.createParallelGroup(
							javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addGroup(
											layout.createParallelGroup(
													javax.swing.GroupLayout.Alignment.LEADING)
													.addGroup(
															layout.createSequentialGroup()
																	.addGap(65,
																			65,
																			65)
																	.addComponent(
																			jScrollPane2,
																			javax.swing.GroupLayout.PREFERRED_SIZE,
																			javax.swing.GroupLayout.DEFAULT_SIZE,
																			javax.swing.GroupLayout.PREFERRED_SIZE))
													.addGroup(
															layout.createSequentialGroup()
																	.addGap(178,
																			178,
																			178)
																	.addComponent(
																			list1,
																			javax.swing.GroupLayout.PREFERRED_SIZE,
																			javax.swing.GroupLayout.DEFAULT_SIZE,
																			javax.swing.GroupLayout.PREFERRED_SIZE)))
									.addContainerGap(91, Short.MAX_VALUE)));
			layout.setVerticalGroup(layout.createParallelGroup(
					javax.swing.GroupLayout.Alignment.LEADING).addGroup(
					layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jScrollPane2,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(43, 43, 43)
							.addComponent(list1,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(87, Short.MAX_VALUE)));
		}// </editor-fold>


	
	public static void main(String[] args) {
		ArrayList<String> classesChosen = new ArrayList<String>();
		classesChosen.add("1");
		classesChosen.add("2");
		classesChosen.add("3");
		
		ScheduleDisplay ja = new ScheduleDisplay(classesChosen);
		
		
	}
	
	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea2;
	private java.awt.List list1;
	// End of variables declaration
}


